/* English with Mariami — curriculum expansion for grades 2–4 */
window.MARIAMI_CURRICULUM={
2:{title:'მე-2 კლასი — Beginner',units:[
{title:'👋 Greetings & Me',words:[['hello','გამარჯობა'],['goodbye','ნახვამდის'],['name','სახელი'],['boy','ბიჭი'],['girl','გოგო'],['friend','მეგობარი'],['happy','ბედნიერი'],['sad','სევდიანი']],grammar:['I am / You are','My name is…','This is…','I am not…'],speaking:['Hello! What is your name?','My name is Nino.','How are you?','I am fine, thank you.']},
{title:'👨‍👩‍👧 Family',words:[['mother','დედა'],['father','მამა'],['sister','და'],['brother','ძმა'],['grandmother','ბებია'],['grandfather','ბაბუა'],['family','ოჯახი'],['baby','ჩვილი']],grammar:['my / your','his / her','This is my…'],speaking:['This is my mother.','Who is he? He is my brother.']},
{title:'🏫 School',words:[['school','სკოლა'],['teacher','მასწავლებელი'],['student','მოსწავლე'],['book','წიგნი'],['pen','კალამი'],['pencil','ფანქარი'],['desk','მერხი'],['bag','ჩანთა']],grammar:['a / an','this / that','there is / there are'],speaking:['Open your book.','What is this? It is a pencil.']},
{title:'🍎 Food & Drinks',words:[['apple','ვაშლი'],['banana','ბანანი'],['bread','პური'],['cheese','ყველი'],['milk','რძე'],['water','წყალი'],['juice','წვენი'],['egg','კვერცხი']],grammar:['I like…','I do not like…','Do you like…?'],speaking:['Do you like apples?','Yes, I do.','No, I do not.']},
{title:'🐶 Animals',words:[['dog','ძაღლი'],['cat','კატა'],['bird','ჩიტი'],['fish','თევზი'],['horse','ცხენი'],['rabbit','კურდღელი'],['lion','ლომი'],['elephant','სპილო']],grammar:['It is…','It has…','It can…'],speaking:['What animal is it?','It is a dog. It can run.']},
{title:'🎨 Colors & Numbers',words:[['red','წითელი'],['blue','ლურჯი'],['green','მწვანე'],['yellow','ყვითელი'],['black','შავი'],['white','თეთრი'],['one','ერთი'],['two','ორი'],['three','სამი'],['ten','ათი'],['twenty','ოცი'],['one hundred','ასი']],grammar:['How many…?','What color is…?'],speaking:['What color is it?','It is blue.','How many apples? Five apples.']}
]},
3:{title:'მე-3 კლასი — Elementary',units:[
{title:'🌅 Daily Routine',words:[['morning','დილა'],['wake up','გაღვიძება'],['breakfast','საუზმე'],['school','სკოლა'],['lunch','სადილი'],['homework','საშინაო დავალება'],['evening','საღამო'],['sleep','ძილი']],grammar:['Present Simple','do / does','always / usually / sometimes / never'],speaking:['What time do you get up?','I get up at seven.','I usually have breakfast at home.']},
{title:'🏠 My Home',words:[['kitchen','სამზარეულო'],['bedroom','საძინებელი'],['bathroom','აბაზანა'],['garden','ბაღი'],['chair','სკამი'],['table','მაგიდა'],['bed','საწოლი'],['door','კარი']],grammar:['There is / There are','prepositions: in, on, under, next to'],speaking:['Where is the book?','It is on the table.']},
{title:'🌦️ Weather',words:[['sunny','მზიანი'],['rainy','წვიმიანი'],['cloudy','მოღრუბლული'],['windy','ქარიანი'],['snowy','თოვლიანი'],['hot','ცხელი'],['cold','ცივი'],['weather','ამინდი']],grammar:['It is…','Is it…?','Present Continuous basics'],speaking:['What is the weather like?','It is sunny and warm.']},
{title:'⚽ Hobbies & Free Time',words:[['play','თამაში'],['read','კითხვა'],['draw','ხატვა'],['swim','ცურვა'],['run','სირბილი'],['football','ფეხბურთი'],['music','მუსიკა'],['game','თამაში']],grammar:['like + -ing','can / cannot'],speaking:['What do you like doing?','I like playing football.']},
{title:'🛍️ Shopping',words:[['shop','მაღაზია'],['price','ფასი'],['money','ფული'],['cheap','იაფი'],['expensive','ძვირი'],['buy','ყიდვა'],['want','სურვილი'],['please','გთხოვთ']],grammar:['How much is…?','I would like…','some / any'],speaking:['How much is this?','It is five pounds.','I would like a red T-shirt, please.']}
]},
4:{title:'მე-4 კლასი — Strong Elementary',units:[
{title:'🕒 Present, Past & Future',words:[['today','დღეს'],['yesterday','გუშინ'],['tomorrow','ხვალ'],['usually','ჩვეულებრივ'],['sometimes','ზოგჯერ'],['already','უკვე'],['later','მოგვიანებით'],['next week','შემდეგ კვირას']],grammar:['Present Simple vs Continuous','Past Simple','will / be going to'],speaking:['What are you doing now?','I am studying English.','What did you do yesterday?','I visited my grandmother.']},
{title:'🌍 Travel & Places',words:[['journey','მოგზაურობა'],['airport','აეროპორტი'],['ticket','ბილეთი'],['hotel','სასტუმრო'],['country','ქვეყანა'],['city','ქალაქი'],['map','რუკა'],['station','სადგური']],grammar:['Past Simple questions','Wh- questions','prepositions of place'],speaking:['Where are you going?','I am going to London.','Where is the station?']},
{title:'🥗 Healthy Life',words:[['healthy','ჯანსაღი'],['exercise','ვარჯიში'],['vegetable','ბოსტნეული'],['fruit','ხილი'],['breakfast','საუზმე'],['strong','ძლიერი'],['tired','დაღლილი'],['sleep','ძილი']],grammar:['should / should not','must / must not','countable / uncountable nouns'],speaking:['What should I do?','You should drink water and exercise.']},
{title:'🌟 Describing People & Things',words:[['beautiful','ლამაზი'],['different','განსხვავებული'],['interesting','საინტერესო'],['important','მნიშვნელოვანი'],['friendly','მეგობრული'],['clever','ჭკვიანი'],['strong','ძლიერი'],['careful','ფრთხილი']],grammar:['comparatives','superlatives','because / but / and'],speaking:['Which is bigger?','The elephant is bigger than the horse.']},
{title:'💬 Real Conversations',words:[['help','დახმარება'],['problem','პრობლემა'],['question','კითხვა'],['answer','პასუხი'],['understand','გაგება'],['repeat','გამეორება'],['please','გთხოვთ'],['sorry','ბოდიში']],grammar:['Could you…?','Can I…?','Would you like…?'],speaking:['Could you help me, please?','Of course.','Could you repeat that?','Sure!']}
]}
};
