const DATA = {
  2: {
    name: 'მე-2 კლასი',

    words: [
      ['hello','გამარჯობა'],
      ['hi','სალამი'],
      ['good morning','დილა მშვიდობისა'],
      ['goodbye','ნახვამდის'],
      ['please','გთხოვ'],
      ['thank you','მადლობა'],
      ['sorry','ბოდიში'],
      ['yes','დიახ'],
      ['no','არა'],
      ['mother','დედა'],
      ['father','მამა'],
      ['sister','და'],
      ['brother','ძმა'],
      ['family','ოჯახი'],
      ['teacher','მასწავლებელი'],
      ['student','მოსწავლე'],
      ['school','სკოლა'],
      ['book','წიგნი'],
      ['pen','კალამი'],
      ['pencil','ფანქარი'],
      ['bag','ჩანთა'],
      ['chair','სკამი'],
      ['house','სახლი'],
      ['room','ოთახი'],
      ['door','კარი'],
      ['window','ფანჯარა'],
      ['bed','საწოლი'],
      ['table','მაგიდა'],
      ['dog','ძაღლი'],
      ['cat','კატა'],
      ['bird','ჩიტი'],
      ['fish','თევზი'],
      ['horse','ცხენი'],
      ['rabbit','კურდღელი'],
      ['lion','ლომი'],
      ['apple','ვაშლი'],
      ['banana','ბანანი'],
      ['bread','პური'],
      ['milk','რძე'],
      ['water','წყალი'],
      ['red','წითელი'],
      ['blue','ლურჯი'],
      ['green','მწვანე'],
      ['yellow','ყვითელი'],
      ['black','შავი'],
      ['white','თეთრი'],
      ['pink','ვარდისფერი'],
      ['happy','ბედნიერი'],
      ['sad','მოწყენილი'],
      ['big','დიდი'],
      ['small','პატარა'],
      ['hot','ცხელი'],
      ['cold','ცივი'],
      ['sun','მზე'],
      ['rain','წვიმა'],
      ['tree','ხე'],
      ['flower','ყვავილი'],
      ['head','თავი'],
      ['eye','თვალი'],
      ['ear','ყური'],
      ['nose','ცხვირი'],
      ['hand','ხელი'],
      ['leg','ფეხი'],
      ['run','რბენა'],
      ['walk','სიარული'],
      ['jump','ხტომა'],
      ['read','კითხვა'],
      ['write','წერა'],
      ['eat','ჭამა'],
      ['drink','სმა']
    ],

    numbers: [
      ['one','ერთი'],
      ['two','ორი'],
      ['three','სამი'],
      ['four','ოთხი'],
      ['five','ხუთი'],
      ['six','ექვსი'],
      ['seven','შვიდი'],
      ['eight','რვა'],
      ['nine','ცხრა'],
      ['ten','ათი'],
      ['eleven','თერთმეტი'],
      ['twelve','თორმეტი'],
      ['thirteen','ცამეტი'],
      ['fourteen','თოთხმეტი'],
      ['fifteen','თხუთმეტი'],
      ['sixteen','თექვსმეტი'],
      ['seventeen','ჩვიდმეტი'],
      ['eighteen','თვრამეტი'],
      ['nineteen','ცხრამეტი'],
      ['twenty','ოცი']
    ],

    grammar: [
      ['I am','მე ვარ'],
      ['You are','შენ ხარ'],
      ['He is','ის არის'],
      ['She is','ის არის'],
      ['This is','ეს არის'],
      ['I have','მე მაქვს'],
      ['I like','მე მომწონს']
    ],

    dialogue: [
      ['Hello!','გამარჯობა!'],
      ['What is your name?','რა გქვია?'],
      ['My name is Ana.','მე ანა მქვია.'],
      ['How are you?','როგორ ხარ?'],
      ["I'm fine, thank you.",'კარგად ვარ, მადლობა.']
    ]
  },

  3: {
    name: 'მე-3 კლასი',

    words: [
      ['morning','დილა'],
      ['afternoon','შუადღე'],
      ['evening','საღამო'],
      ['today','დღეს'],
      ['tomorrow','ხვალ'],
      ['yesterday','გუშინ'],
      ['Monday','ორშაბათი'],
      ['Tuesday','სამშაბათი'],
      ['Wednesday','ოთხშაბათი'],
      ['Thursday','ხუთშაბათი'],
      ['Friday','პარასკევი'],
      ['Saturday','შაბათი'],
      ['Sunday','კვირა'],
      ['friend','მეგობარი'],
      ['classmate','კლასელი'],
      ['homework','საშინაო დავალება'],
      ['lesson','გაკვეთილი'],
      ['question','კითხვა'],
      ['answer','პასუხი'],
      ['story','ამბავი'],
      ['picture','სურათი'],
      ['computer','კომპიუტერი'],
      ['phone','ტელეფონი'],
      ['garden','ბაღი'],
      ['kitchen','სამზარეულო'],
      ['bathroom','სააბაზანო'],
      ['breakfast','საუზმე'],
      ['lunch','სადილი'],
      ['dinner','ვახშამი'],
      ['break','დასვენება'],
      ['shirt','პერანგი'],
      ['shoes','ფეხსაცმელი'],
      ['jacket','ჟაკეტი'],
      ['trousers','შარვალი'],
      ['weather','ამინდი'],
      ['sunny','მზიანი'],
      ['cloudy','მოღრუბლული'],
      ['windy','ქარიანი'],
      ['snowy','თოვლიანი'],
      ['beautiful','ლამაზი'],
      ['clever','ჭკვიანი'],
      ['kind','კეთილი'],
      ['strong','ძლიერი'],
      ['fast','სწრაფი'],
      ['slow','ნელი'],
      ['open','გახსნა'],
      ['close','დახურვა'],
      ['listen','მოსმენა'],
      ['speak','საუბარი'],
      ['learn','სწავლა'],
      ['play','თამაში'],
      ['help','დახმარება'],
      ['make','გაკეთება'],
      ['go','წასვლა'],
      ['come','მოსვლა'],
      ['see','ნახვა'],
      ['know','ცოდნა'],
      ['want','სურვილი'],
      ['need','საჭიროება'],
      ['can','შეძლება'],
      ['must','უნდა'],
      ['always','ყოველთვის'],
      ['sometimes','ზოგჯერ'],
      ['never','არასოდეს'],
      ['near','ახლოს'],
      ['far','შორს'],
      ['left','მარცხნივ'],
      ['right','მარჯვნივ']
    ],

    numbers: [
      ['twenty-one','ოცდაერთი'],
      ['thirty','ოცდაათი'],
      ['forty','ორმოცი'],
      ['fifty','ორმოცდაათი'],
      ['sixty','სამოცი'],
      ['seventy','სამოცდაათი'],
      ['eighty','ოთხმოცი'],
      ['ninety','ოთხმოცდაათი'],
      ['one hundred','ასი']
    ],

    grammar: [
      ['I have got','მე მაქვს'],
      ['There is','არის'],
      ['There are','არის რამდენიმე'],
      ['I can','მე შემიძლია'],
      ['I cannot','მე არ შემიძლია'],
      ['Do you like?','მოგწონს?'],
      ['Where do you live?','სად ცხოვრობ?']
    ],

    dialogue: [
      ['Where do you live?','სად ცხოვრობ?'],
      ['I live in Kutaisi.','მე ქუთაისში ვცხოვრობ.'],
      ['What do you like?','რა მოგწონს?'],
      ['I like English and games.','ინგლისური და თამაშები მომწონს.']
    ]
  },

  4: {
    name: 'მე-4 კლასი',

    words: [
      ['adventure','თავგადასავალი'],
      ['airport','აეროპორტი'],
      ['library','ბიბლიოთეკა'],
      ['museum','მუზეუმი'],
      ['hospital','საავადმყოფო'],
      ['restaurant','რესტორანი'],
      ['market','ბაზარი'],
      ['station','სადგური'],
      ['country','ქვეყანა'],
      ['city','ქალაქი'],
      ['village','სოფელი'],
      ['language','ენა'],
      ['English','ინგლისური'],
      ['Georgian','ქართული'],
      ['holiday','არდადეგები'],
      ['birthday','დაბადების დღე'],
      ['present','საჩუქარი'],
      ['exercise','ვარჯიში'],
      ['healthy','ჯანმრთელი'],
      ['important','მნიშვნელოვანი'],
      ['different','განსხვავებული'],
      ['interesting','საინტერესო'],
      ['difficult','რთული'],
      ['easy','ადვილი'],
      ['early','ადრე'],
      ['late','გვიან'],
      ['first','პირველი'],
      ['second','მეორე'],
      ['third','მესამე'],
      ['fourth','მეოთხე'],
      ['fifth','მეხუთე'],
      ['favorite','საყვარელი'],
      ['because','იმიტომ რომ'],
      ['before','მანამდე'],
      ['after','შემდეგ'],
      ['between','შორის'],
      ['under','ქვეშ'],
      ['above','ზემოთ'],
      ['behind','უკან'],
      ['travel','მოგზაურობა'],
      ['visit','მონახულება'],
      ['arrive','ჩამოსვლა'],
      ['leave','წასვლა'],
      ['remember','დამახსოვრება'],
      ['understand','გაგება'],
      ['explain','ახსნა'],
      ['describe','აღწერა'],
      ['choose','არჩევა'],
      ['practice','ვარჯიში'],
      ['improve','გაუმჯობესება'],
      ['pronounce','გამოთქმა'],
      ['translate','თარგმნა'],
      ['create','შექმნა'],
      ['enjoy','სიამოვნების მიღება'],
      ['together','ერთად'],
      ['usually','ჩვეულებრივ'],
      ['often','ხშირად'],
      ['quickly','სწრაფად']
    ],

    numbers: [
      ['one hundred','ასი'],
      ['two hundred','ორასი'],
      ['three hundred','სამასი'],
      ['five hundred','ხუთასი'],
      ['one thousand','ათასი'],
      ['twentieth','მეოცე']
    ],

    grammar: [
      ['Present Simple','აწმყო მარტივი დრო'],
      ['I play','მე ვთამაშობ'],
      ['She plays','ის თამაშობს'],
      ['Do you play?','თამაშობ?'],
      ['Does he play?','ის თამაშობს?'],
      ["I don't know",'მე არ ვიცი'],
      ['I am going','მე მივდივარ'],
      ['I like reading','მიყვარს კითხვა']
    ],

    dialogue: [
      ['What is your favorite subject?','რომელია შენი საყვარელი საგანი?'],
      ['My favorite subject is English.','ჩემი საყვარელი საგანი ინგლისურია.'],
      ['Why do you learn English?','რატომ სწავლობ ინგლისურს?'],
      ['Because it is interesting.','იმიტომ, რომ საინტერესოა.'],
      ["Let's learn together!",'მოდი ერთად ვისწავლოთ!']
    ]
  }
};
