(()=>{'use strict';
/* Grade 2 frontend: Supabase is the source of truth for L1-L20 curriculum content. */
const KEY='grade2_complete_v1';
const FALLBACK=[];
const db=window.__ENGLISH_MARIAMI_SUPABASE_CLIENT||window.supabaseClient||window.supabase;
const G2_START=1,G2_END=20;
let lessons=[],current=null,tab='overview',quizState=null;
let p=load();
function load(){try{return Object.assign({xp:0,stars:0,done:[],daily:'',words:[],bestQuiz:0,quizAttempts:0,rewards:{quizPassed:{}}},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(_){return {xp:0,stars:0,done:[],daily:'',words:[],bestQuiz:0,quizAttempts:0,rewards:{quizPassed:{}}}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(p))}catch(_){};document.dispatchEvent(new CustomEvent('grade2progress',{detail:p}))}
function esc(s){return String(s??'').replace(/[&<>\\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[m]))}
function arr(v){if(Array.isArray(v))return v;if(v==null)return[];if(typeof v==='string'){try{const x=JSON.parse(v);return Array.isArray(x)?x:[x]}catch(_){return v.split(/\\r?\\n/).map(x=>x.trim()).filter(Boolean)}}return[v]}
function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(t||''));u.lang='en-US';u.rate=.82;speechSynthesis.speak(u)}
function stats(){const done=p.done.filter(i=>Number.isInteger(Number(i))&&Number(i)>=0&&Number(i)<G2_END).length;const $=id=>document.getElementById(id);if(!$('xpValue'))return;$('xpValue').textContent=Number(p.xp)||0;$('starValue').textContent=Number(p.stars)||0;$('streakValue').textContent=Math.min(30,done);$('levelValue').textContent=Math.max(1,Math.floor((Number(p.xp)||0)/100)+1);const pct=Math.round(Math.min(done,G2_END)/G2_END*100);$('progressText').textContent=pct+'%';$('progressBar').style.width=pct+'%'}
function render(){const g=document.querySelector('#lessonGrid');if(!g)return;g.innerHTML=lessons.map((w,i)=>{const n=Number(w.lesson_number||i+1),done=p.done.includes(n-1);return `<article class="lesson ${done?'completed':''}" style="--c:${['#00efff','#7c7cff','#ff4fcf','#a66cff','#00d9a6','#ff9d3d','#ff5f8a','#39b7ff','#9b7cff','#4de7ff','#49ff9a','#ffd84d'][i%12]}" data-i="${i}"><div class="mission-no">${n===G2_END?'FINAL MISSION':'MISSION '+String(n).padStart(2,'0')}</div><div class="scene">${['👋','👨‍👩‍👧','🎨','🔢','🧍','🐾','🍎','🧸','🎒','🌦️','👕','⏰','🙂','🛏️','🍽️','🛁','📏','😊','🌡️','⚡'][i%20]}</div><h3>${esc(w.title||w.topic||'Lesson '+n)}</h3><p class="ka">${esc(w.topic||'')}</p><p class="desc">${esc(w.description||'')} ${w._words!=null?'• '+w._words+' learning words':''}</p><div class="lesson-foot"><span class="stars">${done?'★★★★★':'☆☆☆☆☆'}</span><button class="enter">${done?'REPLAY':'ENTER →'}</button></div></article>`}).join('');stats()}
async function loadLessons(){
 if(!db?.from){console.warn('[Grade 2] Supabase client unavailable');render();return}
 const r=await db.from('lessons').select('id,grade,lesson_number,title,topic,description,image_url,audio_url,grammar_rule,grammar_examples,listening_text,speaking_phrases,reading_text,exercises').eq('grade',2).gte('lesson_number',G2_START).lte('lesson_number',G2_END).order('lesson_number',{ascending:true});
 if(r.error)throw r.error;
 const rows=r.data||[];const ids=rows.map(x=>x.id).filter(Boolean);let words=[],quizzes=[];
 if(ids.length){const [wr,qr]=await Promise.all([db.from('lesson_words').select('id,lesson_id,word,translation,emoji,image_url,audio_url,sort_order').in('lesson_id',ids).order('sort_order',{ascending:true}),db.from('lesson_quizzes').select('id,lesson_id,question,options,correct_answer,sort_order').in('lesson_id',ids).order('sort_order',{ascending:true})]);if(wr.error)throw wr.error;if(qr.error)throw qr.error;words=wr.data||[];quizzes=qr.data||[]}
 const wm=new Map(),qm=new Map();words.forEach(x=>{const k=String(x.lesson_id);if(!wm.has(k))wm.set(k,[]);wm.get(k).push(x)});quizzes.forEach(x=>{const k=String(x.lesson_id);if(!qm.has(k))qm.set(k,[]);qm.get(k).push(x)});
 lessons=rows.map(x=>({...x,words:wm.get(String(x.id))||[],quizzes:qm.get(String(x.id))||[],_words:(wm.get(String(x.id))||[]).length}));
 if(lessons.length<G2_END){FALLBACK.forEach(f=>{if(!lessons.some(x=>Number(x.lesson_number)===f.lesson_number))lessons.push({...f,words:[],quizzes:[]})});lessons.sort((a,b)=>Number(a.lesson_number)-Number(b.lesson_number))}
 render()
}
function open(i){current=i;tab='overview';quizState=null;const m=document.querySelector('#modal');m.classList.add('open');m.setAttribute('aria-hidden','false');draw()}
function close(){const m=document.querySelector('#modal');m.classList.remove('open');m.setAttribute('aria-hidden','true');current=null}
function draw(){const w=lessons[current];if(!w)return;const root=document.querySelector('#modalContent');const words=w.words||[],qs=w.quizzes||[];root.innerHTML=`<div class="mission">GRADE 2 • ${String(w.lesson_number).padStart(2,'0')} • ${esc(w.title||w.topic||'Lesson')}</div><h2 class="modal-title">${esc(w.title||w.topic||'Lesson')}</h2><p class="modal-ka">${esc(w.topic||'')}</p><div class="tabs"><button class="tab ${tab==='overview'?'active':''}" data-tab="overview">📘 OVERVIEW</button><button class="tab ${tab==='words'?'active':''}" data-tab="words">📚 WORDS (${words.length})</button><button class="tab ${tab==='grammar'?'active':''}" data-tab="grammar">🎯 GRAMMAR</button><button class="tab ${tab==='listening'?'active':''}" data-tab="listening">🎧 LISTENING</button><button class="tab ${tab==='speaking'?'active':''}" data-tab="speaking">🗣️ SPEAKING</button><button class="tab ${tab==='reading'?'active':''}" data-tab="reading">📖 READING</button><button class="tab ${tab==='exercises'?'active':''}" data-tab="exercises">✏️ EXERCISES</button><button class="tab ${tab==='quiz'?'active':''}" data-tab="quiz">🧩 QUIZ (${qs.length})</button></div><div id="activity"></div>`;
 const a=document.querySelector('#activity');
 if(tab==='overview')overview(a,w);if(tab==='words')wordsView(a,w);if(tab==='grammar')grammarView(a,w);if(tab==='listening')listeningView(a,w);if(tab==='speaking')speakingView(a,w);if(tab==='reading')readingView(a,w);if(tab==='exercises')exercisesView(a,w);if(tab==='quiz')quizView(a,w)
}
function box(title,body){return `<div class="result"><h3>${title}</h3>${body}</div>`}
function overview(a,w){a.innerHTML=box('📘 Lesson Target',`<p>${esc(w.description||w.topic||'')}</p><p><b>🎯 Topic:</b> ${esc(w.topic||'')}</p><p><b>📚 Vocabulary:</b> ${(w.words||[]).length}</p><p><b>🧩 Quiz:</b> ${(w.quizzes||[]).length}</p><p class="small">Complete the quiz with at least 75% to unlock mission completion.</p>`)}
function wordsView(a,w){const words=w.words||[];a.innerHTML=words.length?`<div class="words">${words.map(x=>`<div class="word-card"><b>${esc((x.emoji||'')+' '+(x.word||''))}</b><div class="ka">${esc(x.translation||'')}</div>${x.example?`<p>${esc(x.example)}</p>`:''}<button class="listen" data-speak="${esc(x.word||'')}">🔊 LISTEN</button>${x.audio_url?`<button class="listen" data-audio="${esc(x.audio_url)}">▶️ AUDIO</button>`:''}</div>`).join('')}</div>`:box('Vocabulary','No vocabulary found for this lesson.')}
function grammarView(a,w){const ex=arr(w.grammar_examples);a.innerHTML=box('🎯 Grammar',`<p class="reading-text">${esc(w.grammar_rule||'Grammar target is not available.')}</p>${ex.length?`<div class="vocab">${ex.map(x=>`<div class="word-card"><p>${esc(x)}</p><button class="listen" data-speak="${esc(x)}">🔊 LISTEN</button></div>`).join('')}</div>`:''}`)}
function listeningView(a,w){a.innerHTML=box('🎧 Listening',`<p class="reading-text">${esc(w.listening_text||'Listening text is not available.')}</p>${w.audio_url?`<audio controls preload="none" src="${esc(w.audio_url)}"></audio>`:`<button class="action" data-speak="${esc(w.listening_text||'')}">🔊 PLAY WITH VOICE</button>`}`)}
function speakingView(a,w){const xs=arr(w.speaking_phrases);a.innerHTML=box('🗣️ Speaking',xs.length?`<div class="vocab">${xs.map(x=>`<div class="word-card"><b>${esc(x)}</b><button class="listen" data-speak="${esc(x)}">🔊 PRACTICE</button></div>`).join('')}</div>`:'Speaking phrases are not available.')}
function readingView(a,w){a.innerHTML=box('📖 Reading',`<p class="reading-text">${esc(w.reading_text||'Reading text is not available.')}</p>${w.reading_text?`<button class="action" data-speak="${esc(w.reading_text)}">🔊 READ ALOUD</button>`:''}`)}
function exercisesView(a,w){const xs=arr(w.exercises);a.innerHTML=box('✏️ Exercises',xs.length?`<ol>${xs.map(x=>`<li style="margin:10px 0">${esc(x)}</li>`).join('')}</ol>`:'Exercises are not available.')}
function normalizeOptions(v){const x=arr(v);return x.map(String).filter(Boolean)}
function quizView(a,w){const qs=w.quizzes||[];if(!qs.length){a.innerHTML=box('🧩 Quiz','No quiz questions found.');return}if(!quizState||quizState.lesson!==current)quizState={lesson:current,index:0,score:0,answered:false};const q=qs[quizState.index];a.innerHTML=`<div class="lesson-box"><p><b>QUESTION ${quizState.index+1} / ${qs.length}</b></p><h3>${esc(q.question)}</h3><div class="actions">${normalizeOptions(q.options).map(o=>`<button class="action secondary" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div><p id="quizFeedback"></p></div>`}
function finishQuiz(w){const total=(w.quizzes||[]).length,score=quizState.score,pct=total?Math.round(score/total*100):0;const n=Number(w.lesson_number)-1;const passed=pct>=75;if(passed&&!p.done.includes(n)){p.done=[...p.done,n];p.xp=(Number(p.xp)||0)+25;p.stars=(Number(p.stars)||0)+1}p.bestQuiz=Math.max(Number(p.bestQuiz)||0,pct);p.quizAttempts=(Number(p.quizAttempts)||0)+1;p.rewards=p.rewards||{quizPassed:{}};p.rewards.quizPassed=Object.assign({},p.rewards.quizPassed,{[current]:passed});save();stats();draw();setTimeout(()=>{const f=document.querySelector('#quizFeedback');if(f)f.innerHTML=`<b>${passed?'✅ MISSION PASSED':'🔄 TRY AGAIN'}</b> — ${score}/${total} (${pct}%)${passed?' • +25 XP':''}`},0)}
document.addEventListener('click',e=>{const lesson=e.target.closest('.lesson');if(lesson){open(Number(lesson.dataset.i));return}const tabBtn=e.target.closest('[data-tab]');if(tabBtn&&current!==null){tab=tabBtn.dataset.tab;quizState=tab==='quiz'?quizState:null;draw();return}if(e.target.closest('#closeModal')){close();return}const sp=e.target.closest('[data-speak]');if(sp){speak(sp.dataset.speak);return}const aud=e.target.closest('[data-audio]');if(aud){new Audio(aud.dataset.audio).play().catch(()=>{});return}const ans=e.target.closest('[data-answer]');if(ans&&current!==null){const w=lessons[current],q=w.quizzes?.[quizState.index];if(!q||quizState.answered)return;quizState.answered=true;const ok=String(ans.dataset.answer)===String(q.correct_answer);quizState.score+=ok?1:0;const f=document.querySelector('#quizFeedback');if(f)f.textContent=ok?'✅ Correct!':'❌ Not quite.';setTimeout(()=>{quizState.index++;quizState.answered=false;if(quizState.index>=(w.quizzes||[]).length){finishQuiz(w)}else draw()},650)}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&current!==null)close()});
async function daily(){const today=new Date().toISOString().slice(0,10);if(p.daily===today)return;if(p.daily!==today){p.daily=today;p.xp=(Number(p.xp)||0)+10;save();stats();const b=document.querySelector('#dailyBtn');if(b)b.textContent='✓ COMPLETED'}}
document.addEventListener('DOMContentLoaded',async()=>{try{await loadLessons()}catch(e){console.error('[Grade 2 Load]',e);render()}stats();const c=document.querySelector('#continueBtn');if(c)c.onclick=()=>{const i=lessons.findIndex((w,idx)=>!p.done.includes(Number(w.lesson_number)-1));open(i<0?lessons.length-1:i)};const r=document.querySelector('#reviewBtn');if(r)r.onclick=()=>open(Math.max(0,lessons.length-1));const d=document.querySelector('#dailyBtn');if(d)d.onclick=daily;const m=document.querySelector('#megaPracticeBtn');if(m)m.addEventListener('click',()=>document.dispatchEvent(new CustomEvent('grade2-open-mega')));document.querySelector('#closeModal')?.addEventListener('click',close)})
})();