const KEY='grade2_neon_progress_v1';let state={xp:0,stars:0,done:[],daily:''};try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){}const $=id=>document.getElementById(id);
const lessons=[
['👋','Hello & Introductions','მისალმება და გაცნობა',['hello|გამარჯობა|Hello, my friend!','hi|სალამი|Hi, Anna!','good morning|დილა მშვიდობისა|Good morning, teacher.','goodbye|ნახვამდის|Goodbye!','name|სახელი|My name is Nika.','friend|მეგობარი|This is my friend.','teacher|მასწავლებელი|She is my teacher.','student|მოსწავლე|I am a student.','boy|ბიჭი|He is a boy.','girl|გოგო|She is a girl.','welcome|კეთილი იყოს შენი მობრძანება|Welcome!','thanks|მადლობა|Thanks, teacher!']],
['🔢','Numbers & Counting','რიცხვები და თვლა',['one|ერთი|I have one book.','two|ორი|I have two pencils.','three|სამი|Three cats.','four|ოთხი|Four birds.','five|ხუთი|Five apples.','six|ექვსი|Six students.','seven|შვიდი|Seven stars.','eight|რვა|Eight books.','nine|ცხრა|Nine balls.','ten|ათი|Ten fingers.','twenty|ოცი|Twenty students.','hundred|ასი|One hundred stars.']],
['🎨','Colors & Shapes','ფერები და ფორმები',['red|წითელი|The apple is red.','blue|ლურჯი|The sky is blue.','green|მწვანე|The grass is green.','yellow|ყვითელი|The sun is yellow.','orange|ნარინჯისფერი|The orange is orange.','pink|ვარდისფერი|The flower is pink.','black|შავი|The cat is black.','white|თეთრი|The snow is white.','circle|წრე|This is a circle.','square|კვადრატი|This is a square.','triangle|სამკუთხედი|This is a triangle.','star|ვარსკვლავი|I see a star.']],
['👨‍👩‍👧','My Family','ჩემი ოჯახი',['family|ოჯახი|I love my family.','mother|დედა|My mother is kind.','father|მამა|My father is tall.','sister|და|I have a sister.','brother|ძმა|I have a brother.','grandmother|ბებია|My grandmother is nice.','grandfather|ბაბუა|My grandfather is funny.','baby|ბავშვი|The baby is small.','parents|მშობლები|My parents are kind.','love|სიყვარული|I love my family.','kind|კეთილი|She is kind.','happy|ბედნიერი|My family is happy.']],
['🏠','My Home','ჩემი სახლი',['home|სახლი|This is my home.','house|სახლი|My house is big.','room|ოთახი|This is my room.','bedroom|საძინებელი|I sleep in my bedroom.','kitchen|სამზარეულო|Mum is in the kitchen.','bathroom|აბაზანა|The bathroom is clean.','door|კარი|Open the door.','window|ფანჯარა|The window is open.','table|მაგიდა|The book is on the table.','chair|სკამი|Sit on the chair.','bed|საწოლი|My bed is soft.','garden|ბაღი|I play in the garden.']],
['🐾','Animals','ცხოველები',['dog|ძაღლი|The dog is happy.','cat|კატა|The cat is small.','bird|ჩიტი|The bird can fly.','fish|თევზი|The fish can swim.','horse|ცხენი|The horse is big.','cow|ძროხა|The cow is white.','lion|ლომი|The lion is strong.','tiger|ვეფხვი|The tiger is fast.','elephant|სპილო|The elephant is big.','monkey|მაიმუნი|The monkey is funny.','rabbit|კურდღელი|The rabbit is small.','bear|დათვი|The bear is strong.']],
['🍎','Food & Drinks','საკვები და სასმელები',['apple|ვაშლი|I like apples.','banana|ბანანი|The banana is yellow.','orange|ფორთოხალი|I eat an orange.','bread|პური|I like bread.','cheese|ყველი|The cheese is good.','egg|კვერცხი|I eat an egg.','rice|ბრინჯი|I like rice.','milk|რძე|I drink milk.','water|წყალი|I drink water.','juice|წვენი|I like juice.','cake|ნამცხვარი|The cake is sweet.','hungry|მშიერი|I am hungry.']],
['🎒','My School','ჩემი სკოლა',['school|სკოლა|I go to school.','classroom|საკლასო ოთახი|This is my classroom.','book|წიგნი|I have a book.','pen|კალამი|This is my pen.','pencil|ფანქარი|I have a pencil.','bag|ჩანთა|My bag is blue.','desk|მერხი|My book is on the desk.','board|დაფა|The teacher writes on the board.','lesson|გაკვეთილი|The lesson is fun.','read|კითხვა|I can read.','write|წერა|I can write.','learn|სწავლა|I like to learn.']],
['☀️','Weather & Seasons','ამინდი და სეზონები',['sunny|მზიანი|It is sunny today.','rainy|წვიმიანი|It is rainy today.','cloudy|ღრუბლიანი|The sky is cloudy.','windy|ქარიანი|It is windy.','snowy|თოვლიანი|It is snowy.','hot|ცხელი|It is hot today.','cold|ცივი|It is cold today.','spring|გაზაფხული|Spring is beautiful.','summer|ზაფხული|Summer is hot.','autumn|შემოდგომა|Autumn is colorful.','winter|ზამთარი|Winter is cold.','weather|ამინდი|The weather is nice.']],
['🧍','My Body','ჩემი სხეული',['head|თავი|This is my head.','hair|თმა|My hair is brown.','eye|თვალი|I have two eyes.','ear|ყური|I have two ears.','nose|ცხვირი|This is my nose.','mouth|პირი|Open your mouth.','hand|ხელი|Raise your hand.','finger|თითი|I have ten fingers.','leg|ფეხი|My leg is strong.','foot|ტერფი|My foot is small.','arm|მკლავი|My arm is strong.','body|სხეული|This is my body.']],
['❤️','Feelings & Daily Life','გრძნობები და ყოველდღიური ცხოვრება',['happy|ბედნიერი|I am happy.','sad|სევდიანი|I am sad.','tired|დაღლილი|I am tired.','angry|გაბრაზებული|He is angry.','scared|შეშინებული|She is scared.','excited|აღელვებული|I am excited.','sleep|ძილი|I sleep at night.','wake up|გაღვიძება|I wake up early.','eat|ჭამა|I eat breakfast.','drink|სმა|I drink water.','play|თამაში|I play with friends.','help|დახმარება|I help my mum.']],
['🏆','Final Mission','საბოლოო გამეორება',['hello|გამარჯობა|Hello, my friend!','family|ოჯახი|I love my family.','school|სკოლა|I go to school.','book|წიგნი|I read a book.','dog|ძაღლი|The dog is happy.','apple|ვაშლი|I like apples.','blue|ლურჯი|The sky is blue.','sunny|მზიანი|It is sunny.','happy|ბედნიერი|I am happy.','water|წყალი|I drink water.','winter|ზამთარი|Winter is cold.','mother|დედა|My mother is kind.']]
];
function save(){localStorage.setItem(KEY,JSON.stringify(state));update();render()}function update(){$('xp').textContent=state.xp;$('stars').textContent=state.stars;$('level').textContent=Math.floor(state.xp/100)+1;$('progress').style.width=(state.xp%100)+'%'}function speak(t){if(!window.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u)}
function render(){$('lessons').innerHTML=lessons.map((l,i)=>`<article class="lesson ${state.done.includes(i)?'done':''}" onclick="openLesson(${i})"><div class="mission">MISSION ${String(i+1).padStart(2,'0')}</div><div class="icon">${l[0]}</div><h3>${l[1]}</h3><div class="ka">${l[2]}</div><p>12 English words • listening • games • practice</p><div class="foot"><span>12 WORDS</span><span>${state.done.includes(i)?'✅ DONE':'▶ OPEN'}</span></div></article>`).join('')}
function openLesson(i){const l=lessons[i];$('content').innerHTML=`<h2>${l[0]} ${l[1]}</h2><p class="ka">${l[2]}</p><div class="tabs"><button class="tab" onclick="showWords(${i})">📚 WORDS</button><button class="tab" onclick="showFlash(${i})">🧠 FLASHCARDS</button><button class="tab" onclick="showQuiz(${i})">🎯 QUIZ</button><button class="tab" onclick="showMatch(${i})">🧩 MATCH</button><button class="tab" onclick="showSentence(${i})">✍️ SENTENCE</button></div><div id="activity"></div>`;$('modal').classList.add('show');showWords(i)}function closeModal(){$('modal').classList.remove('show');window.speechSynthesis?.cancel()}
function showWords(i){const ws=lessons[i][3].map(x=>x.split('|'));$('activity').innerHTML=`<div class="words">${ws.map(w=>`<div class="word"><b>${w[0]}</b><div class="ka">${w[1]}</div><p>${w[2]}</p><button class="listen" onclick="speak('${w[0].replaceAll("'",'')}')">🔊 Listen</button></div>`).join('')}</div><button onclick="complete(${i})">✅ COMPLETE MISSION +50 XP</button>`}
function showFlash(i){const ws=lessons[i][3].map(x=>x.split('|'));let n=0,flip=false;function draw(){$('activity').innerHTML=`<div class="flash"><div class="flashcard" onclick="flip=!flip;draw()"><div><b>${flip?ws[n][1]:ws[n][0]}</b><br><span>${flip?ws[n][0]:'Tap to reveal ქართული'}</span><p>${n+1}/${ws.length}</p></div></div><button onclick="speak('${ws[n][0]}')">🔊 HEAR</button><button onclick="n=(n+1)%ws.length;flip=false;draw()">NEXT →</button></div>`}draw()}
function showQuiz(i){const ws=lessons[i][3].map(x=>x.split('|')).slice(0,8);let n=0,score=0;function draw(){if(n===ws.length){state.xp+=score*10;save();$('activity').innerHTML=`<div class="score"><strong>${score}/${ws.length}</strong><h2>${score>=6?'🚀 GREAT JOB!':'⚡ KEEP PRACTICING!'}</h2><p>+${score*10} XP</p></div>`;return}const w=ws[n],opts=[w[1],ws[(n+2)%ws.length][1],ws[(n+4)%ws.length][1]].sort(()=>Math.random()-.5);$('activity').innerHTML=`<div class="question">What does <span class="cyan">${w[0]}</span> mean?</div><div class="options">${opts.map(o=>`<button class="option" onclick="quizPick(this,${JSON.stringify(o)},${JSON.stringify(w[1])})">${o}</button>`).join('')}</div>`}window.quizPick=(e,a,c)=>{document.querySelectorAll('.option').forEach(x=>x.disabled=true);if(a===c){e.classList.add('correct');score++}else{e.classList.add('wrong');[...document.querySelectorAll('.option')].find(x=>x.textContent===c)?.classList.add('correct')}setTimeout(()=>{n++;draw()},500)};draw()}
function showMatch(i){const ws=lessons[i][3].map(x=>x.split('|')).slice(0,8);let selected=null,done=0;$('activity').innerHTML=`<p>Match English with Georgian — შეაერთე წყვილები.</p><div class="match"><div>${ws.map(w=>`<button class="matchitem" data-en="${w[0]}" onclick="selEn(this)">${w[0]}</button>`).join('')}</div><div>${[...ws].sort(()=>Math.random()-.5).map(w=>`<button class="matchitem" data-ka="${w[1]}" onclick="selKa(this)">${w[1]}</button>`).join('')}</div></div>`;window.selEn=e=>{document.querySelectorAll('[data-en]').forEach(x=>x.classList.remove('active'));e.classList.add('active');selected=e};window.selKa=e=>{if(!selected)return;const w=ws.find(x=>x[0]===selected.dataset.en);if(w[1]===e.dataset.ka){selected.classList.add('correct');e.classList.add('correct');selected.disabled=e.disabled=true;selected=null;done++;if(done===ws.length){state.xp+=40;state.stars++;save();$('activity').innerHTML='<div class="score"><strong>100%</strong><h2>🎉 PERFECT MATCH!</h2></div>'}}else e.classList.add('wrong')}}
function showSentence(){const examples=[['My name is Nika',['My','name','is','Nika']],['I love my family',['I','love','my','family']],['I go to school',['I','go','to','school']],['The dog is happy',['The','dog','is','happy']]];let n=0,chosen=[];function draw(){chosen=[];const s=examples[n];$('activity').innerHTML=`<p>ააწყვე სწორი წინადადება.</p><div id="sentenceBox" class="sentence"></div><div>${[...s[1]].sort(()=>Math.random()-.5).map(w=>`<button class="token" onclick="addToken(this,${JSON.stringify(w)})">${w}</button>`).join('')}</div><button onclick="checkSentence()">CHECK ✓</button><div id="msg"></div>`}window.addToken=(e,w)=>{e.disabled=true;chosen.push(w);$('sentenceBox').innerHTML+=`<span class="token">${w}</span> `};window.checkSentence=()=>{if(chosen.join(' ')===examples[n][0]){$('msg').innerHTML='<b style="color:#21ff9a">✅ Correct!</b>';setTimeout(()=>{n++;n<examples.length?draw():(state.xp+=30,state.stars++,save(),$('activity').innerHTML='<div class="score"><strong>🎉</strong><h2>ALL SENTENCES COMPLETE!</h2></div>')},500)}else $('msg').innerHTML='<b style="color:#ff416c">❌ Try again!</b>'};draw()}
function complete(i){if(!state.done.includes(i)){state.done.push(i);state.xp+=50;state.stars++;save()}closeModal()}function continueMission(){const i=lessons.findIndex((_,i)=>!state.done.includes(i));openLesson(i<0?11:i)}function finalReview(){$('content').innerHTML=`<div class="score"><strong>${Math.round(state.done.length/12*100)}%</strong><h2>${state.done.length===12?'🏆 ENGLISH MASTER!':'🚀 KEEP GOING!'}</h2><p>Completed ${state.done.length}/12 missions.<br>დასრულებული გაქვს ${state.done.length}/12 გაკვეთილი.</p><button onclick="ultimateQuiz()">🎯 ULTIMATE QUIZ</button></div>`;$('modal').classList.add('show')}
function ultimateQuiz(){const all=lessons.flatMap(l=>l[3].map(x=>x.split('|'))).sort(()=>Math.random()-.5).slice(0,15);let n=0,score=0;function draw(){if(n===all.length){const p=Math.round(score/all.length*100);state.xp+=score*10;if(p>=70)state.stars+=3;save();$('content').innerHTML=`<div class="score"><strong>${p}%</strong><h2>${p>=90?'🏆 ENGLISH MASTER!':'🚀 GREAT JOB!'}</h2><p>${score}/${all.length}</p></div>`;return}const w=all[n],opts=[w[1],all[(n+3)%all.length][1],all[(n+7)%all.length][1]].sort(()=>Math.random()-.5);$('content').innerHTML=`<h2>🏆 ULTIMATE QUIZ</h2><div id="activity"><div class="question">${w[0]}</div><div class="options">${opts.map(o=>`<button class="option" onclick="uPick(this,${JSON.stringify(o)},${JSON.stringify(w[1])})">${o}</button>`).join('')}</div></div>`}window.uPick=(e,a,c)=>{document.querySelectorAll('.option').forEach(x=>x.disabled=true);if(a===c){e.classList.add('correct');score++}else e.classList.add('wrong');setTimeout(()=>{n++;draw()},450)};draw()}
function dailyChallenge(){const d=new Date().toISOString().slice(0,10);if(state.daily===d){alert('Daily challenge already complete!');return}const w=lessons[Math.floor(Math.random()*11)][3][Math.floor(Math.random()*12)].split('|');$('content').innerHTML=`<div class="score"><strong>${w[0]}</strong><h2>${w[1]}</h2><p>${w[2]}</p><button onclick="speak('${w[0]}')">🔊 LISTEN</button><button onclick="state.daily='${d}';state.xp+=25;state.stars++;save();closeModal()">✅ I LEARNED IT +25 XP</button></div>`;$('modal').classList.add('show')}
$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});update();render();