(function(){'use strict';
const baseWorlds=[['01','🧩','Grammar Core','Build stronger sentences and grammar patterns.'],['02','📖','Story Station','Read, understand and retell short stories.'],['03','🗣️','Speak Lab','Practice conversations and everyday English.'],['04','🔤','Word Forge','Expand vocabulary and use new words.'],['05','🌍','World Explorer','Places, cultures and useful travel English.'],['06','🔬','Science Hub','Explore simple science in English.'],['07','🎭','Drama Zone','Characters, dialogue and expressive English.'],['08','🎵','Music Pulse','Rhythm, listening and useful music English.'],['09','💻','Tech Lab','Technology words and digital life.'],['10','🧠','Brain Quest','Logic, questions and problem solving.'],['11','🌟','Star Academy','Mixed skills challenge.'],['12','🏆','Final Core','Final Grade 4 mastery mission.']];
const content=window.GRADE4_FUTURISTIC_CONTENT||{worlds:[]};
const worlds=baseWorlds.map((w,i)=>{const c=content.worlds[i]||{};return{base:w,words:Array.isArray(c.words)?c.words:[],ka:c.ka||'',icon:c.icon||w[1]};});
const KEY='grade4UniverseProgress';let s={xp:0,stars:0,done:[]};
try{const old=JSON.parse(localStorage.getItem(KEY)||'{}');if(old&&typeof old==='object')s={...s,...old};s.done=Array.isArray(s.done)?s.done:[];s.xp=Number.isFinite(+s.xp)?+s.xp:0;s.stars=Number.isFinite(+s.stars)?+s.stars:0;}catch(e){}
const reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function save(){try{localStorage.setItem(KEY,JSON.stringify(s));}catch(e){}updateStats();}
function updateStats(){const x=document.querySelector('#xp'),st=document.querySelector('#stars'),d=document.querySelector('#done');if(x)x.textContent=s.xp;if(st)st.textContent=s.stars;if(d)d.textContent=s.done.length;}
function esc(v){return String(v).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
function render(){const r=document.querySelector('#missions');if(!r)return;r.innerHTML=worlds.map((w,i)=>{const b=w.base,preview=w.words.slice(0,3).map(v=>esc(v[0])+' — '+esc(v[1])).join(' • ');return `<article class="mission u-holo ${s.done.includes(i)?'done':''}" data-i="${i}" tabindex="0"><span class="num">WORLD ${b[0]}</span><span class="icon">${w.icon}</span><h3>${esc(b[2])}</h3><p>${esc(b[3])}</p>${w.ka?`<small class="g4-ka">${esc(w.ka)}</small>`:''}${preview?`<div class="g4-vocab-preview">${preview}</div>`:''}<button class="g4-open" type="button">OPEN MISSION →</button></article>`}).join('');r.querySelectorAll('.mission').forEach(c=>{c.addEventListener('click',e=>{if(!e.target.closest('button')||e.target.closest('.g4-open'))openMission(+c.dataset.i);});c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openMission(+c.dataset.i);}});});}
function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u);}
function openMission(i){const w=worlds[i],b=w.base,modal=document.createElement('div');modal.className='g4-vocab-modal';modal.innerHTML=`<div class="g4-vocab-dialog" role="dialog" aria-modal="true" aria-labelledby="g4-title"><button class="g4-close" type="button" aria-label="Close">×</button><div class="g4-modal-icon">${w.icon}</div><span class="num">WORLD ${b[0]}</span><h2 id="g4-title">${esc(b[2])}</h2><p>${esc(w.ka||b[3])}</p><div class="g4-word-list">${w.words.map(v=>`<div class="g4-word"><div><strong>${esc(v[0])}</strong><span>${esc(v[1])}</span></div><button type="button" data-speak="${esc(v[0])}" aria-label="Listen to ${esc(v[0])}">🔊</button></div>`).join('')}</div><button class="g4-complete" type="button">✓ COMPLETE MISSION • +25 XP</button></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.g4-close').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close();const b=e.target.closest('[data-speak]');if(b)speak(b.getAttribute('data-speak'));});modal.querySelector('.g4-complete').onclick=()=>complete(i,modal);if(!reduced){requestAnimationFrame(()=>modal.classList.add('show'));}else modal.classList.add('show');modal.querySelector('.g4-close').focus();}
function complete(i,modal){if(s.done.includes(i)){modal.querySelector('.g4-complete').textContent='✓ WORLD ALREADY COMPLETE';return;}s.done.push(i);s.xp+=25;s.stars+=1;save();render();modal.remove();}
function robot(){if(document.querySelector('.g4-robot'))return;const r=document.createElement('button');r.className='g4-robot';r.type='button';r.setAttribute('aria-label','AI Robot');r.innerHTML='<span>🤖</span>';r.title='Tap me!';r.addEventListener('click',()=>{r.classList.remove('dance');void r.offsetWidth;r.classList.add('dance');});document.body.appendChild(r);}
const start=document.querySelector('#start'),review=document.querySelector('#review');if(start)start.onclick=()=>{const n=worlds.findIndex((_,i)=>!s.done.includes(i));document.querySelector(`[data-i="${n<0?11:n}"]`)?.scrollIntoView({behavior:reduced?'auto':'smooth',block:'center'});};if(review)review.onclick=()=>{review.textContent=`🏆 ${s.done.length}/12 • ${s.xp} XP`;setTimeout(()=>{review.textContent='🏆 MISSION STATUS';},1800);};
updateStats();render();robot();
})();