(function(){'use strict';
const KEY='grade4UniverseProgress';
let state={xp:0,stars:0,streak:0,done:[],last:null,quizRewards:{},quizPassed:{}};
try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){}
state.done=Array.isArray(state.done)?state.done:[];state.xp=+state.xp||0;state.stars=+state.stars||0;state.streak=+state.streak||0;state.quizRewards=state.quizRewards&&typeof state.quizRewards==='object'?state.quizRewards:{};state.quizPassed=state.quizPassed&&typeof state.quizPassed==='object'?state.quizPassed:{};
const client=window.__ENGLISH_MARIAMI_SUPABASE_CLIENT||window.supabaseClient;
const fallback=window.GRADE4_FUTURISTIC_CONTENT||{worlds:[],lessons:[]};const worlds=fallback.worlds||[];let lessons=[];
const arr=v=>Array.isArray(v)?v:[];const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}updateStats()}
function updateStats(){[['#xp',state.xp],['#stars',state.stars],['#streak',state.streak],['#done',state.done.length]].forEach(([q,v])=>{const e=document.querySelector(q);if(e)e.textContent=v});const total=lessons.length||60,p=Math.min(100,Math.round(state.done.length/total*100));const bar=document.querySelector('#progressBar'),txt=document.querySelector('#progressText');if(bar)bar.style.width=p+'%';if(txt)txt.textContent=state.done.length+'/'+total+' • '+p+'%';const next=document.querySelector('#nextMission');if(next){const n=lessons.find(l=>!state.done.includes(l.id));next.textContent=n?'Next mission: L'+n.lesson_number+' • '+n.title:'🎉 Universe complete — Champion status unlocked'}}
function worldIndex(l){const count=Math.max(1,worlds.length),size=Math.max(1,Math.ceil((lessons.length||1)/count));return Math.min(count-1,Math.max(0,Math.floor((Number(l.lesson_number)-1)/size)))}
function render(){const root=document.querySelector('#missions');if(!root)return;root.innerHTML=worlds.map((w,i)=>{const group=lessons.filter(l=>worldIndex(l)===i),done=group.filter(l=>state.done.includes(l.id)).length,wc=group.reduce((n,l)=>n+arr(l.words).length,0),qc=group.reduce((n,l)=>n+arr(l.quizzes).length,0);return `<article class="mission u-holo ${done===group.length?'done':''}" data-world="${i}" tabindex="0"><span class="num">WORLD ${esc(w.id)} • ${done}/${group.length} COMPLETE</span><span class="icon">${w.icon}</span><h3>${esc(w.title)}</h3><span class="g4-ka">${esc(w.ka)}</span><p>Focused Grade 4 training. Grammar, vocabulary, reading, listening and challenges stay inside this world.</p><div class="g4-vocab-preview">${group.length} lessons • ${wc} words • ${qc} quiz questions • 🧩 brain missions</div><button class="g4-open" type="button">OPEN WORLD →</button></article>`}).join('');root.querySelectorAll('.mission').forEach(c=>{const open=()=>openWorld(+c.dataset.world);c.addEventListener('click',open);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
function speak(text){if(!('speechSynthesis'in window)||!text)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text));u.lang='en-US';u.rate=.82;speechSynthesis.speak(u)}
function lessonMarkup(l){const ws=arr(l.words),qs=arr(l.quizzes),ex=arr(l.exercises),phr=arr(l.speaking_phrases),ge=arr(l.grammar_examples),done=state.done.includes(l.id),passed=!!state.quizPassed[l.id],canComplete=!qs.length||passed;return `<section class="g4-live-lesson"><div class="g4-live-lesson-head"><span class="num">LESSON ${esc(l.lesson_number)} • ${done?'COMPLETED':'READY'}</span><h3>${esc(l.title)}</h3><p>${esc(l.topic)}</p></div>${l.grammar_rule?`<div class="g4-content-box"><b>🧠 GRAMMAR CORE</b><p>${esc(l.grammar_rule)}</p><ul>${ge.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${l.reading_text?`<div class="g4-content-box"><b>📖 READING SCAN</b><p>${esc(l.reading_text)}</p></div>`:''}${l.listening_text?`<div class="g4-content-box"><b>🎧 LISTENING LAB</b><p>${esc(l.listening_text)}</p><button class="g4-speak-text" data-text="${esc(l.listening_text)}">🔊 LISTEN & REPEAT</button></div>`:''}${phr.length?`<div class="g4-content-box"><b>🗣️ SPEAKING LAB</b><ul>${phr.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${ex.length?`<div class="g4-content-box"><b>✍️ PRACTICE DECK</b><ul>${ex.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${ws.length?`<div class="g4-live-words"><b>🔤 VOCABULARY VAULT • ${ws.length} WORDS</b>${ws.map(w=>`<div class="g4-word"><div><strong>${esc(w.word)}</strong><span>${esc(w.translation)} ${esc(w.emoji||'')}</span></div><button type="button" data-speak="${esc(w.word)}">🔊</button></div>`).join('')}</div>`:''}${qs.length?`<details class="g4-quiz" open><summary>🎯 QUIZ ARENA • ${qs.length} QUESTIONS</summary>${qs.map((q,n)=>`<div class="quiz-q" data-correct="${esc(q.correct_answer)}"><b>${n+1}. ${esc(q.question)}</b><div class="quiz-options">${arr(q.options).map(o=>`<button type="button" class="g4-option" data-option="${esc(o)}">${esc(o)}</button>`).join('')}</div></div>`).join('')}</details>`:''}<button class="g4-complete" data-complete="${esc(l.id)}" ${done||!canComplete?'disabled':''}>${done?'✓ COMPLETED • XP EARNED':canComplete?'✓ COMPLETE LESSON • +25 XP':'🔒 PASS QUIZ ≥70% TO COMPLETE'}</button></section>`}
function openWorld(i){const group=lessons.filter(l=>worldIndex(l)===i),w=worlds[i];if(!w)return;const modal=document.createElement('div');modal.className='g4-vocab-modal';modal.innerHTML=`<div class="g4-vocab-dialog g4-live-dialog" role="dialog" aria-modal="true"><button class="g4-close" type="button" aria-label="Close">×</button><div class="g4-modal-icon">${w.icon}</div><span class="num">WORLD ${esc(w.id)} • ${group.length} MISSIONS</span><h2>${esc(w.title)}</h2><p>${esc(w.ka)} — this world keeps one learning focus at a time.</p><div>${group.map(lessonMarkup).join('')}</div></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.g4-close').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close();const s=e.target.closest('[data-speak]');if(s)speak(s.dataset.speak);const t=e.target.closest('[data-text]');if(t)speak(t.dataset.text);const c=e.target.closest('[data-complete]');if(c)complete(c.dataset.complete,modal);const o=e.target.closest('[data-option]');if(o)answerQuiz(o)});requestAnimationFrame(()=>modal.classList.add('show'));modal.querySelector('.g4-close').focus()}
function refreshQuizPass(lesson){const id=lesson?.querySelector('[data-complete]')?.dataset.complete;if(!id)return;const qs=Array.from(lesson.querySelectorAll('.quiz-q'));if(!qs.length)return;const answered=qs.every(q=>q.querySelector('.quiz-correct'));if(!answered)return;const correct=qs.filter(q=>!q.querySelector('.quiz-wrong')).length,passed=correct/qs.length>=.7;if(passed&&!state.quizPassed[id]){state.quizPassed[id]=true;save()}const b=lesson.querySelector('[data-complete]');if(b&&!state.done.includes(id)){b.disabled=!passed;b.textContent=passed?'✓ COMPLETE LESSON • +25 XP':'🔒 PASS QUIZ ≥70% TO COMPLETE'}}
async function recordActivity(id,score){if(!client)return;try{await client.rpc('academy_record_activity',{p_activity_type:'lesson',p_activity_id:'grade4-lesson-'+id,p_grade:4,p_score:score,p_points:score})}catch(e){console.warn('[G4] reward activity failed',e)}}
function answerQuiz(btn){const q=btn.closest('.quiz-q');if(!q)return;const ok=btn.dataset.option===q.dataset.correct;q.querySelectorAll('.g4-option').forEach(b=>{b.disabled=true;if(b.dataset.option===q.dataset.correct)b.classList.add('quiz-correct')});btn.classList.add(ok?'quiz-correct':'quiz-wrong');refreshQuizPass(q.closest('.g4-live-lesson'))}
async function complete(id,modal){if(state.done.includes(id))return;const lesson=modal.querySelector(`[data-complete="${CSS.escape(id)}"]`)?.closest('.g4-live-lesson');if(!lesson)return;const qs=Array.from(lesson.querySelectorAll('.quiz-q'));if(qs.length&&!state.quizPassed[id])return;const score=qs.length?Math.round(qs.filter(q=>!q.querySelector('.quiz-wrong')).length/qs.length*100):100;await recordActivity(id,score);state.done.push(id);state.last=Date.now();save();render();const b=modal.querySelector(`[data-complete="${CSS.escape(id)}"]`);if(b){b.textContent='✓ COMPLETED • SAVED TO ACADEMY';b.disabled=true}}
async function load(){let loaded=false;if(client){try{const r=await client.from('lessons').select('id,grade,lesson_number,title,topic,description,grammar_rule,grammar_examples,listening_text,speaking_phrases,reading_text,exercises').eq('grade',4).order('lesson_number',{ascending:true});if(!r.error&&arr(r.data).length){lessons=r.data;const ids=lessons.map(x=>x.id);const [wr,qr]=await Promise.all([client.from('lesson_words').select('id,lesson_id,word,translation,emoji,sort_order').in('lesson_id',ids).order('sort_order',{ascending:true}),client.from('lesson_quizzes').select('id,lesson_id,question,options,correct_answer,sort_order').in('lesson_id',ids).order('sort_order',{ascending:true})]);const words=!wr.error?arr(wr.data):[],quizzes=!qr.error?arr(qr.data):[];const wm=new Map(),qm=new Map();words.forEach(x=>{if(!wm.has(x.lesson_id))wm.set(x.lesson_id,[]);wm.get(x.lesson_id).push(x)});quizzes.forEach(x=>{if(!qm.has(x.lesson_id))qm.set(x.lesson_id,[]);qm.get(x.lesson_id).push(x)});lessons.forEach(x=>{x.words=wm.get(x.id)||[];x.quizzes=qm.get(x.id)||[]});loaded=true}}catch(e){console.warn('Grade 4 live curriculum unavailable; using local curriculum.',e)}}if(!loaded)lessons=arr(fallback.lessons);if(window.applyGrade4ContentExpansion)window.applyGrade4ContentExpansion(lessons);const words=lessons.reduce((n,l)=>n+arr(l.words).length,0),quizzes=lessons.reduce((n,l)=>n+arr(l.quizzes).length,0);const live=document.querySelector('#liveStats');if(live)live.textContent=`⚡ ${lessons.length} LESSONS • ${words} WORDS • ${quizzes} QUIZ QUESTIONS • ${state.done.length} COMPLETED`;render();updateStats()}
function boot(){load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
