/* MAGIC NEON AI ACADEMY — Grade 4 curriculum engine */
(function(){'use strict';
const key='magic-neon-grade-4';
const worlds=[
['Identity & Goals',['identity','strength','challenge','ambition','responsibility','confidence','future','achievement'],'I have learned that knowing my strengths also means accepting areas I need to improve. My goal is to become more confident when I speak English.','What is your goal? — My goal is to speak English more confidently.','Maya reflects on her future. She knows that achievement requires effort, responsibility, and the confidence to learn from mistakes. She writes small goals and reviews her progress each week.','What does Maya review each week?','Her progress','Why is knowing both strengths and weaknesses useful?'],
['Family & Relationships',['relationship','respect','tradition','advice','generation','trust','supportive','memory'],'Our family has different traditions, but we respect one another and share responsibilities at home.','What does the family share? — Responsibilities at home.','David interviews his grandparents about family traditions. He discovers that some customs have changed, while the values of respect and support have remained important across generations.','What has remained important?','Respect and support','How can families preserve traditions while accepting change?'],
['Time & Productivity',['priority','schedule','organize','deadline','routine','focus','balance','efficient'],'I organize my schedule by choosing important tasks first and leaving time for rest.','How do you organize your schedule? — I choose important tasks first.','Nina has three assignments due on Friday. Instead of doing everything at once, she sets priorities, works in focused periods, and checks each deadline. She also protects time for sleep.','What does Nina check?','Each deadline','Why is balance important when planning your time?'],
['Learning & Projects',['investigate','source','evidence','collaborate','draft','revise','present','solution'],'Our team investigates a problem, compares sources, and revises our draft before presenting a solution.','What does the team revise? — The draft.','A group investigates why plastic waste is increasing near their school. They collect evidence, compare reliable sources, collaborate on a proposal, and revise it after receiving feedback.','Why do they revise the proposal?','After receiving feedback','How does evidence improve a project?'],
['Health & Choices',['nutrition','wellbeing','hydration','exercise','decision','habit','moderation','energy'],'Good health involves daily choices such as drinking water, exercising regularly, and eating a balanced diet.','What supports wellbeing? — Healthy daily choices.','Leo learns that wellbeing is not based on one perfect decision. He builds sustainable habits: regular exercise, enough water, balanced meals, and moderation rather than extreme rules.','What kind of habits does Leo build?','Sustainable habits','Why are sustainable habits more useful than extreme rules?'],
['Community & Places',['community','volunteer','neighborhood','facility','public','transport','service','citizen'],'A strong community depends on people who care for shared places and take part in local activities.','Who helps a community? — People who take part and care for shared places.','Students survey their neighborhood and notice that a small library lacks volunteers. They suggest a reading club and a cleaner transport area, then present their ideas to community leaders.','What does the library lack?','Volunteers','What responsibility do citizens have toward shared places?'],
['Style & Decisions',['practical','appearance','quality','material','design','occasion','preference','value'],'I consider quality and purpose before choosing something simply because it looks attractive.','What do you consider before buying? — Quality and purpose.','Sara needs a jacket for school and hiking. She compares material, design, price, and durability instead of choosing only by appearance. Her final choice is practical and long-lasting.','What does Sara compare?','Material, design, price, and durability','What makes a choice practical?'],
['Climate & Environment',['climate','resource','recycle','conserve','pollution','ecosystem','impact','sustainable'],'Small actions can reduce our impact when many people make them consistently.','How can people reduce impact? — By making sustainable choices consistently.','A class studies water use at school. They discover that small leaks waste resources and that unnecessary plastic creates pollution. The class proposes repairs, recycling, and conservation measures.','What do leaks waste?','Resources','Which environmental action would have the greatest impact at your school, and why?'],
['Animals & Science',['adapt','species','researcher','observe','survival','endangered','ecosystem','behavior'],'Researchers observe animals carefully because behavior can reveal how a species adapts to its environment.','Why do researchers observe animals? — To understand adaptation and behavior.','A science team observes birds during different seasons. Their notes show that food availability affects behavior and movement. The researchers use repeated observations rather than one unusual event to support their conclusion.','What affects the birds’ behavior?','Food availability','Why are repeated observations stronger than one unusual event?'],
['Skills & Creativity',['creative','discipline','technique','perform','practice','feedback','talent','improve'],'Talent can help, but disciplined practice and useful feedback are what turn a skill into lasting ability.','What turns skill into ability? — Practice and useful feedback.','Oto wants to improve his guitar performance. He records himself, identifies weak techniques, practices them slowly, and asks his teacher for feedback. Progress is gradual but measurable.','How does Oto find weak techniques?','By recording himself','Why is feedback valuable during practice?'],
['Experiences & Memories',['experience','journey','unexpected','discover','reflect','perspective','moment','lesson'],'An unexpected journey can become valuable when we reflect on what it teaches us.','What can make a journey valuable? — What we learn from it.','During a school trip, heavy rain changes the group’s plan. Instead of returning immediately, the students visit a local science center and discover an exhibit they had not expected. Later they reflect on how flexibility changed the experience.','What changed the group’s plan?','Heavy rain','How can an unexpected change become a positive experience?'],
['Ideas & Opinions',['opinion','argument','reason','evidence','perspective','compare','conclude','respect'],'A strong opinion should be explained with reasons and evidence, while different perspectives should be treated with respect.','What should support an opinion? — Reasons and evidence.','In a class discussion, students compare two solutions to reduce homework stress. They identify evidence, consider different perspectives, and reach a conclusion without attacking people who disagree.','What do students compare?','Two solutions','How can disagreement remain respectful and useful?']
];
const types=['Vocabulary Quest','Dialogue Lab','Reading Mission','Grammar Lab','Thinking Challenge'];
const grammar=[
[['I ___ responsible for my goals.',['am','is','are'],'am'],['She ___ confidence through practice.',['builds','build','building'],'builds'],['They ___ their progress weekly.',['review','reviews','reviewing'],'review'],['We ___ mistakes as learning opportunities.',['see','sees','seeing'],'see'],['He ___ ambitious but realistic goals.',['sets','set','setting'],'sets']],
[['Our family ___ traditions.',['shares','share','sharing'],'shares'],['We ___ one another.',['respect','respects','respecting'],'respect'],['Grandparents ___ valuable advice.',['give','gives','giving'],'give'],['She ___ family memories.',['records','record','recording'],'records'],['They ___ responsibilities.',['share','shares','sharing'],'share']],
[['I ___ my priorities each morning.',['organize','organizes','organizing'],'organize'],['Nina ___ each deadline.',['checks','check','checking'],'checks'],['We ___ focused periods.',['use','uses','using'],'use'],['He ___ time for rest.',['protects','protect','protecting'],'protects'],['They ___ efficiently.',['work','works','working'],'work']],
[['The team ___ reliable sources.',['compares','compare','comparing'],'compares'],['We ___ evidence carefully.',['collect','collects','collecting'],'collect'],['She ___ the draft.',['revises','revise','revising'],'revises'],['They ___ on the proposal.',['collaborate','collaborates','collaborating'],'collaborate'],['He ___ the solution clearly.',['presents','present','presenting'],'presents']],
[['Water ___ our bodies hydrated.',['keeps','keep','keeping'],'keeps'],['I ___ regularly.',['exercise','exercises','exercising'],'exercise'],['She ___ balanced meals.',['chooses','choose','choosing'],'chooses'],['We ___ healthy habits.',['build','builds','building'],'build'],['Good choices ___ energy.',['support','supports','supporting'],'support']],
[['Citizens ___ shared places.',['care for','cares for','caring for'],'care for'],['Our group ___ a survey.',['conducts','conduct','conducting'],'conducts'],['We ___ local activities.',['join','joins','joining'],'join'],['The library ___ volunteers.',['needs','need','needing'],'needs'],['They ___ ideas to leaders.',['present','presents','presenting'],'present']],
[['Sara ___ material before buying.',['compares','compare','comparing'],'compares'],['I ___ practical designs.',['prefer','prefers','preferring'],'prefer'],['He ___ quality highly.',['values','value','valuing'],'values'],['We ___ the occasion.',['consider','considers','considering'],'consider'],['They ___ durable products.',['choose','chooses','choosing'],'choose']],
[['Recycling ___ useful resources.',['conserves','conserve','conserving'],'conserves'],['We ___ plastic when possible.',['recycle','recycles','recycling'],'recycle'],['Pollution ___ ecosystems.',['affects','affect','affecting'],'affects'],['They ___ water carefully.',['conserve','conserves','conserving'],'conserve'],['Small actions ___ an impact.',['make','makes','making'],'make']],
[['Researchers ___ animal behavior.',['observe','observes','observing'],'observe'],['A species ___ to conditions.',['adapts','adapt','adapting'],'adapts'],['We ___ repeated observations.',['need','needs','needing'],'need'],['Scientists ___ evidence.',['use','uses','using'],'use'],['Animals ___ to survive.',['adapt','adapts','adapting'],'adapt']],
[['Oto ___ every day.',['practices','practice','practicing'],'practices'],['I ___ feedback.',['value','values','valuing'],'value'],['She ___ her technique.',['improves','improve','improving'],'improves'],['We ___ weak areas.',['identify','identifies','identifying'],'identify'],['They ___ progress over time.',['measure','measures','measuring'],'measure']],
[['Rain ___ the plan.',['changes','change','changing'],'changes'],['We ___ new places.',['discover','discovers','discovering'],'discover'],['She ___ on experiences.',['reflects','reflect','reflecting'],'reflects'],['They ___ flexible.',['remain','remains','remaining'],'remain'],['He ___ the lesson.',['remembers','remember','remembering'],'remembers']],
[['A good argument ___ reasons.',['needs','need','needing'],'needs'],['We ___ evidence.',['compare','compares','comparing'],'compare'],['She ___ different perspectives.',['respects','respect','respecting'],'respects'],['They ___ a conclusion.',['reach','reaches','reaching'],'reach'],['He ___ his opinion clearly.',['explains','explain','explaining'],'explains']]
];
const distract=['A random detail','The opposite idea'];
const defaults={current:1,done:[],stars:0,streak:0};let state=defaults;try{const x=JSON.parse(localStorage.getItem(key)||'null');if(x&&typeof x==='object')state={...defaults,...x,done:Array.isArray(x.done)?x.done:[]}}catch(e){}
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const save=()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch(e){}};const speak=t=>{if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}};const shuffle=a=>[...a].sort(()=>Math.random()-.5);const world=n=>worlds[Math.floor((n-1)/5)%12];
function mission(n,L){const [topic,words,dialogue,reply,read,q,a,think]=L,m=(n-1)%5;if(m===0){const target=words[(n*3)%words.length],opts=shuffle([target,...words.filter(x=>x!==target).slice(0,2)]);return ['Listening Word Quest','Listen and identify the Grade 4 vocabulary word.',`<button class="btn" data-speak="${esc(target)}">🔊 Play word</button><div class="choicegrid">${opts.map(x=>`<button class="btn choice" data-ok="${x===target}">${esc(x)}</button>`).join('')}</div><div class="quizmsg"></div>`]};if(m===1){const p=reply.split('—');const correct=(p[p.length-1]||reply).trim();return ['Dialogue Lab','Select the response that completes the exchange.',`<p class="dialogue">${esc(dialogue)}</p><button class="btn" data-speak="${esc(dialogue)}">🔊 Listen</button><div class="choicegrid">${shuffle([correct,...distract]).map(x=>`<button class="btn choice" data-ok="${x===correct}">${esc(x)}</button>`).join('')}</div><div class="quizmsg"></div>`]};if(m===2){return ['Reading Mission','Read closely and identify the stated detail.',`<p class="reading">${esc(read)}</p><button class="btn" data-speak="${esc(read)}">🔊 Listen</button><p class="question">${esc(q)}</p><div class="choicegrid">${shuffle([a,...distract]).map(x=>`<button class="btn choice" data-ok="${x===a}">${esc(x)}</button>`).join('')}</div><div class="quizmsg"></div>`]};if(m===3){const g=grammar[Math.floor((n-1)/5)][(n-1)%5];return ['Grammar Lab','Choose the correct verb form.',`<p class="example"><b>${esc(g[0])}</b></p><div class="choicegrid">${shuffle(g[1]).map(x=>`<button class="btn choice" data-ok="${x===g[2]}">${esc(x)}</button>`).join('')}</div><div class="quizmsg"></div>`]};const sk='grade4-answer-'+n;let saved='';try{saved=localStorage.getItem(sk)||''}catch(e){}return ['Critical Thinking','Write 4–6 clear English sentences and support your idea.',`<p class="question">${esc(think)}</p><textarea class="answer" placeholder="Write 4–6 English sentences...">${esc(saved)}</textarea><div class="wordhint">Useful words: ${esc(words.slice(0,4).join(' • '))}</div><button class="btn" data-save="${n}">💾 Save answer</button><div class="save-msg"></div>`]}
function render(){const n=Math.max(1,Math.min(60,Number(state.current)||1)),L=world(n),md=mission(n,L),done=new Set(state.done),topic=L[0],pct=Math.round(done.size/60*100);document.body.innerHTML=`<div class="particles"></div><div class="app"><aside class="side"><div class="brand">MAGIC NEON AI</div><div class="orb"><span>G4</span></div><div class="grade">GRADE 4</div><div class="progress"><i style="width:${pct}%"></i></div><div class="pct">${pct}% COMPLETE</div><div class="missions">${worlds.map((x,i)=>{const s=i*5+1,ok=[0,1,2,3,4].every(k=>done.has(s+k));return `<button class="world ${n>=s&&n<s+5?'active':''}" data-m="${s}">🪐 ${i+1}. ${esc(x[0])} ${ok?'✓':''}</button>`}).join('')}</div></aside><main><div class="top"><div><div class="eyebrow">MAGIC NEON AI ACADEMY • GRADE 4</div><div class="title">${esc(topic)}</div><div class="eyebrow">MISSION ${n} / 60 • ${esc(md[0])}</div></div><div class="stats"><span>⭐ ${state.stars}</span><span>🔥 ${state.streak}</span><span>🏆 ${done.size}/60</span></div></div><section class="hero"><div class="ai">🤖</div><div><h2>AI Companion</h2><p>Think carefully. Grade 4 missions reward clear English, evidence, and independent ideas.</p></div></section><section class="vault"><h3>Vocabulary Vault</h3><div class="chips">${L[1].map(x=>`<span>${esc(x)}</span>`).join('')}</div></section><section class="mission-card"><div class="mission-label">YOUR MISSION</div><h2>${esc(md[0])}</h2><p>${esc(md[1])}</p><div class="mission-task">${md[2]}</div><div class="actions"><button class="btn secondary" data-prev>← Previous</button><button class="btn" data-complete disabled aria-disabled="true" title="Complete the mission task first">Complete Mission →</button></div></section><section class="content-grid"><article><h3>Reading Zone</h3><p>${esc(L[4])}</p></article><article><h3>Comprehension</h3><p>${esc(L[5])}</p><strong>${esc(L[6])}</strong></article></section><nav class="bottom"><button class="btn secondary" data-prev>← Previous</button><button class="btn" data-next>Next Mission →</button></nav></main></div>`;bind(n)}
function bind(n){document.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak));document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{state.current=Number(b.dataset.m);save();render()});document.querySelectorAll('[data-prev]').forEach(b=>b.onclick=()=>{state.current=Math.max(1,n-1);save();render()});document.querySelector('[data-next]').onclick=()=>{state.current=Math.min(60,n+1);save();render()};document.querySelector('[data-complete]').onclick=()=>{if(!state.done.includes(n)){state.done.push(n);state.stars++;state.streak++}state.current=Math.min(60,n+1);save();render()};document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{const msg=b.parentElement.parentElement.querySelector('.quizmsg');msg.textContent=b.dataset.ok==='true'?'✅ Correct! Great work.':'❌ Not quite — read the task again and try once more.'});const s=document.querySelector('[data-save]');if(s)s.onclick=()=>{const input=document.querySelector('.answer');if(input.value.trim().length>=20){try{localStorage.setItem('grade4-answer-'+n,input.value.trim())}catch(e){}const m=document.querySelector('.save-msg');m.textContent='✅ Answer saved. You can complete the mission.'}else{const m=document.querySelector('.save-msg');m.textContent='✍️ Please write at least 20 characters.'}}}
render();
})();