(function(){'use strict';
const content=window.GRADE3_FUTURISTIC_CONTENT||{worlds:[]};
const worlds=(Array.isArray(content.worlds)?content.worlds:[]).map((w,i)=>({id:w.id||String(i+1).padStart(2,'0'),title:w.title||('Mission '+(i+1)),desc:w.desc||'',ka:w.ka||'',category:w.category||'Learning',icon:w.icon||'🚀',words:Array.isArray(w.words)?w.words:[],grammar:w.grammar||'Practice the key grammar point.',listen:w.listen||'Listen and repeat.',quiz:w.quiz||'Complete the challenge.'}));
const key='grade3UniverseProgress';let state={xp:0,stars:0,streak:0,done:[]};try{state={...state,...JSON.parse(localStorage.getItem(key)||'{}')}}catch(e){}if(!Array.isArray(state.done))state.done=[];
function save(){localStorage.setItem(key,JSON.stringify(state));const x=document.querySelector('#xp'),s=document.querySelector('#stars'),t=document.querySelector('#streak');if(x)x.textContent=state.xp;if(s)s.textContent=state.stars;if(t)t.textContent=state.streak;document.dispatchEvent(new CustomEvent('grade3progress',{detail:state}))}
function render(){const root=document.querySelector('#missions');if(!root)return;root.innerHTML=worlds.map((w,i)=>{const preview=w.words.slice(0,3).map(v=>v[0]+' — '+v[1]).join(' • ');return `<article class="mission u-holo ${state.done.includes(i)?'done':''}" data-i="${i}"><span class="num">WORLD ${w.id} • ${w.category.toUpperCase()}</span><span class="icon">${w.icon}</span><h3>${w.title}</h3><p>${w.desc}</p><small class="g3-ka">${w.ka}</small>${preview?`<div class="g3-vocab-preview">${preview}</div>`:''}<button class="g3-open" type="button">OPEN SECTOR →</button></article>`}).join('');root.querySelectorAll('.mission').forEach(card=>card.addEventListener('click',()=>openMission(+card.dataset.i)))}
function openMission(i){const w=worlds[i];let old=document.querySelector('.g3-vocab-modal');if(old)old.remove();const modal=document.createElement('div');modal.className='g3-vocab-modal';modal.innerHTML=`<div class="g3-vocab-dialog" role="dialog" aria-modal="true"><button class="g3-close" aria-label="Close">×</button><div class="g3-modal-icon">${w.icon}</div><div class="num">WORLD ${w.id} • ${w.category}</div><h2>${w.title}</h2><p>${w.desc}</p><section class="g3-section"><h3>🧠 GRAMMAR CORE</h3><p>${w.grammar}</p></section><section class="g3-section"><h3>🎧 LISTENING</h3><p>${w.listen}</p><button class="g3-open" type="button" data-listen="${encodeURIComponent(w.listen)}">🔊 PLAY LISTENING</button></section><section class="g3-section"><h3>📚 VOCABULARY</h3><div class="g3-word-list">${w.words.map(v=>`<div class="g3-word"><div><strong>${v[0]}</strong><span>${v[1]}</span></div><button type="button" data-speak="${v[0]}">🔊</button></div>`).join('')}</div></section><section class="g3-section"><h3>⚡ QUIZ</h3><p>${w.quiz}</p></section><button class="g3-complete" type="button">✓ COMPLETE SECTOR • +25 XP</button></div>`;document.body.appendChild(modal);modal.querySelector('.g3-close').onclick=()=>modal.remove();modal.addEventListener('click',e=>{if(e.target===modal)modal.remove();const speak=e.target.closest('[data-speak]');if(speak&&'speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(speak.dataset.speak);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u)}const listen=e.target.closest('[data-listen]');if(listen&&'speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(decodeURIComponent(listen.dataset.listen));u.lang='en-US';u.rate=.82;speechSynthesis.speak(u)}});modal.querySelector('.g3-complete').onclick=()=>{complete(i);modal.remove()}}
function complete(i){if(state.done.includes(i)){alert('Sector already completed ⭐');return}state.done.push(i);state.xp+=25;state.stars+=1;state.streak=Math.min(7,state.streak+1);save();render();alert(`🚀 ${worlds[i].title} complete! +25 XP ⭐`)}
function initRobotMotion(){const robot=document.querySelector('.ai-robot');if(!robot)return;let raf=0;const move=(x,y)=>{const r=robot.getBoundingClientRect();const dx=Math.max(-1,Math.min(1,(x-(r.left+r.width/2))/Math.max(180,r.width)));const dy=Math.max(-1,Math.min(1,(y-(r.top+r.height/2))/Math.max(180,r.height)));if(raf)cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{robot.style.left=Math.round(dx*55)+'px';robot.style.top=Math.round(dy*38)+'px'})};document.addEventListener('pointermove',e=>{if(e.pointerType==='mouse')move(e.clientX,e.clientY)},{passive:true});robot.addEventListener('pointerdown',e=>move(e.clientX,e.clientY),{passive:true});robot.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse')move(e.clientX,e.clientY)},{passive:true});}
const start=document.querySelector('#start'),review=document.querySelector('#review');if(start)start.addEventListener('click',()=>{const next=worlds.findIndex((_,i)=>!state.done.includes(i));document.querySelector(`[data-i="${next<0?worlds.length-1:next}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})});if(review)review.addEventListener('click',()=>alert(`🏆 ${state.done.length}/${worlds.length} sectors complete • ${state.xp} XP`));save();render();initRobotMotion();
})();
