/* English With Mariami — additive Learning Lab. No XP/Auth/Supabase writes. */
(()=>{
'use strict';
const grade=document.body.classList.contains('u-grade2')?2:document.body.classList.contains('u-grade3')?3:document.body.classList.contains('u-grade4')?4:0;if(!grade)return;
const D={
2:{level:'Beginner',intro:'მარტივი ტექსტები, დიალოგები, წინადადებები და საფიქრალი კითხვები.',alpha:1,words:['family','school','book','friend','room','chair','apple','bird','kite'],texts:[
['My Name Is Nino','Text','Hello! My name is Nino. I am eight years old. I live with my family. I like books and drawing. Every morning I go to school with my brother.','How old is Nino?','eight','Nino likes ______.','drawing'],
['At School','Dialogue','Nino: Hello, Luka! Are you ready for school? | Luka: Yes! I have my bag and my book. | Nino: What is your favorite subject? | Luka: I like English. It is fun!','Why does Luka like English?','because it is fun','Luka has his ______.','book'],
['My Little Room','Description','This is my room. There is a small bed near the wall. My books are on a shelf. A blue ball is under the chair. I keep my room clean.','Where is the blue ball?','under the chair','The books are on a ______.','shelf'],
['A Day in the Park','Text','Mia is in the park with her dad. She sees a dog, two birds and a red kite. The sun is warm. Mia wants to fly the kite, but the wind is too strong.','Why can Mia not fly the kite?','the wind is too strong','Mia sees two ______.','birds'],
['At the Shop','Dialogue','Child: Good morning. Can I have an apple, please? | Shopkeeper: Of course. Red or green? | Child: A green apple, please. Thank you!','Which apple does the child choose?','a green apple','The child says ______.','thank you']]},
3:{level:'Growing Explorer',intro:'უფრო გრძელი ტექსტები, დიალოგები, სურათის/სახლის აღწერა და საუბარი საკუთარ თავზე და ოჯახზე.',alpha:0,words:['family','parents','sister','house','window','picture','jacket','hobby','football','swimming'],texts:[
['About Me','Personal Text','My name is Luka. I am nine years old and I live in Kutaisi. I enjoy football, drawing and reading adventure stories. At school I like English because I can learn new words and talk to my friends.','Why does Luka like English?','he can learn new words and talk to his friends','Luka enjoys ______.','football'],
['My Family','Family Text','There are four people in my family: my mother, my father, my sister and me. My sister Ana is six. She loves music. My father cooks on Saturdays, and we often eat together.','Who loves music?','Ana','There are ______ people in the family.','four'],
['My House','Description','Our house has a bright kitchen, a quiet living room and two bedrooms. My favorite place is the living room because there is a comfortable sofa next to a large window. I often read there after school.','Why is the living room the favorite place?','because there is a comfortable sofa next to a large window','The sofa is next to the ______.','window'],
['A Picture of My Friend','Picture Description','Imagine a picture of Emma. She has long brown hair and a yellow jacket. She is smiling and holding a small green bag. Behind her there is a tall tree.','What color is Emma’s jacket?','yellow','Emma is holding a green ______.','bag'],
['Two New Friends','Dialogue','Mariam: Hi! What is your name? | Giorgi: I am Giorgi. What is your name? | Mariam: I am Mariam. I like music and swimming. | Giorgi: Nice to meet you! I like football.','What does Mariam like?','music and swimming','Giorgi likes ______.','football']]},
4:{level:'Confident Explorer',intro:'უფრო რთული ტექსტები, დიალოგები, აღწერები და ყოველდღიური/ოფიციალური წარდგენა.',alpha:0,words:['introduction','student','languages','grandparents','comfortable','purpose','library','balance','rest'],texts:[
['Introducing Myself — Formal','Formal Introduction','Good morning. My name is Daniel Brown. I am ten years old and I am a student. I live in Georgia with my family. I enjoy reading, playing chess and learning languages. It is a pleasure to meet you.','Which sentence is suitable for a formal introduction?','It is a pleasure to meet you','Daniel enjoys learning ______.','languages'],
['My Family and Our Weekend','Personal Text','There are five people in my family. On Saturdays we usually have breakfast together. My mother enjoys gardening, my father likes cooking, and my younger brother loves building models. In the afternoon we sometimes visit our grandparents.','What does the younger brother enjoy?','building models','The family visits their ______.','grandparents'],
['Describing a House','Description','Our house is small but comfortable. The entrance opens into a bright hallway. The kitchen is opposite the living room, while my bedroom is upstairs. There is a desk beside the window where I do my homework.','Where does the speaker do homework?','at a desk beside the window','The bedroom is ______.','upstairs'],
['At the Information Desk','Dialogue','Student: Excuse me. Could you tell me where the library is? | Assistant: Certainly. It is on the second floor, next to the science room. | Student: Thank you. Is it open this afternoon? | Assistant: Yes, until five o’clock.','Where is the library?','on the second floor next to the science room','The library is open until ______.','five o’clock'],
['A Day in My Life','Personal Text','I usually wake up at seven o’clock. After breakfast I walk to school. In the afternoon I finish my homework before I play outside. In the evening I read for twenty minutes. I try to keep a good balance between study, play and rest.','What does the speaker do before playing outside?','finishes homework','The speaker reads for ______ minutes.','twenty']]}
}[grade];
const speak=t=>{if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=grade===2?.78:grade===3?.88:.95;speechSynthesis.speak(u)};
const E=(t,a,h)=>{const e=document.createElement(t);for(const k in a)e.setAttribute(k,a[k]);if(h!==undefined)e.innerHTML=h;return e};
const root=E('section',{class:'learning-lab','aria-label':'Extra learning lab'});root.innerHTML='<div class="learning-lab-head"><div><span class="u-badge">LEARNING LAB</span><h2>Read • Listen • Think • Play</h2><p>'+D.intro+'</p></div><div class="lab-note">Grade '+grade+' • '+D.level+'</div></div><div class="learning-lab-tabs" role="tablist"></div><div class="learning-lab-content"></div>';
const tabs=root.querySelector('.learning-lab-tabs'),out=root.querySelector('.learning-lab-content'),P={};
const labels={texts:'📖 Texts & Dialogues',listening:'🔊 Listening',practice:'✏️ Practice',games:'🎮 Mini Games'};
if(D.alpha)labels.alphabet='🔤 Alphabet';
Object.keys(labels).forEach(id=>{const b=E('button',{class:'learning-lab-tab',type:'button',role:'tab','aria-selected':id==='texts'},labels[id]);b.onclick=()=>show(id);tabs.appendChild(b)});
function get(id){if(P[id])return P[id];P[id]=E('div',{class:'learning-lab-panel',id:'lab-'+id});out.appendChild(P[id]);return P[id]}
function show(id){Object.values(P).forEach(x=>x.classList.remove('is-active'));tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-selected',b.textContent===labels[id]));const p=get(id);p.classList.add('is-active');if(!p.dataset.ready)render(id,p);}
function render(id,p){p.dataset.ready='1';
if(id==='texts')p.innerHTML='<div class="lab-grid">'+D.texts.map((x,i)=>{const body=x[2].includes(' | ')?'<div class="lab-dialogue">'+x[2].split(' | ').map(v=>'<div class="lab-line">'+v+'</div>').join('')+'</div>':'<p>'+x[2]+'</p>';return '<article class="lab-card"><h3>'+(i+1)+'. '+x[0]+'</h3><div class="lab-note">'+x[1]+'</div>'+body+'<div class="lab-actions"><button class="lab-btn" data-s="'+i+'">🔊 Listen</button><button class="lab-btn" data-q="'+i+'">💡 Think</button></div><div class="lab-question" id="q-'+i+'" hidden><b>Think:</b> '+x[3]+'</div></article>'}).join('')+'</div>';
if(id==='texts'){p.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>speak(D.texts[b.dataset.s][2].replaceAll(' | ',' ')));p.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const q=p.querySelector('#q-'+b.dataset.q);q.hidden=!q.hidden;b.textContent=q.hidden?'💡 Think':'💡 Hide question'})}
if(id==='listening')p.innerHTML='<div class="lab-grid">'+D.texts.map((x,i)=>'<article class="lab-card"><h3>Listening '+(i+1)+': '+x[0]+'</h3><p class="lab-note">Listen twice: first for the idea, then for details.</p><button class="lab-btn" data-l="'+i+'">▶ Play English</button><div class="lab-question"><b>After listening:</b> '+x[3]+'</div><div class="lab-feedback" id="lf-'+i+'"></div><div class="lab-actions"><button class="lab-btn" data-u="'+i+'">I understood it</button></div></article>').join('')+'</div>';
if(id==='listening'){p.querySelectorAll('[data-l]').forEach(b=>b.onclick=()=>speak(D.texts[b.dataset.l][2].replaceAll(' | ',' ')));p.querySelectorAll('[data-u]').forEach(b=>b.onclick=()=>p.querySelector('#lf-'+b.dataset.u).textContent='✅ Great! Now say one sentence about what you heard.')}
if(id==='practice')p.innerHTML='<div class="lab-grid">'+D.texts.map((x,i)=>'<article class="lab-card"><h3>'+x[0]+' — Fill the word</h3><p>'+x[5].replace('______','<span class="lab-blank">______</span>')+'</p><div class="lab-actions">'+[x[6],...D.words.filter(w=>w!==x[6]).slice(0,2)].map(w=>'<button class="lab-btn" data-f="'+encodeURIComponent(w)+'" data-i="'+i+'">'+w+'</button>').join('')+'</div><div class="lab-feedback" id="pf-'+i+'"></div></article>').join('')+'</div>';
if(id==='practice')p.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{const i=b.dataset.i,ok=decodeURIComponent(b.dataset.f).toLowerCase()===D.texts[i][6].toLowerCase();p.querySelector('#pf-'+i).textContent=ok?'✅ Correct!':'Try again — read the sentence carefully.'});
if(id==='games'){let score=0,i=0;p.innerHTML='<div class="lab-grid"><article class="lab-card lab-game"><h3>🎯 Missing Word</h3><p id="gp">Choose the word that completes the sentence.</p><div class="lab-game-options" id="go"></div><div class="lab-score" id="gs">Score: 0</div></article><article class="lab-card lab-game"><h3>🧠 Quick Choice</h3><p>Which word is related to <b>'+D.words[0]+'</b>?</p><div class="lab-game-options"><button class="lab-btn" data-c="1">'+D.words[1]+'</button><button class="lab-btn" data-c="0">'+(grade===2?'banana':'window')+'</button></div><div class="lab-feedback" id="cf"></div></article></div>';const next=()=>{const x=D.texts[i++%D.texts.length],opts=[x[6],...D.words.filter(w=>w!==x[6]).slice(0,2)].sort(()=>Math.random()-.5);p.querySelector('#gp').textContent=x[5];p.querySelector('#go').innerHTML=opts.map(w=>'<button class="lab-btn" data-g="'+encodeURIComponent(w)+'">'+w+'</button>').join('');p.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>{if(decodeURIComponent(b.dataset.g)===x[6]){score++;p.querySelector('#gs').textContent='Score: '+score+' ⭐'}next()})};next();p.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>p.querySelector('#cf').textContent=b.dataset.c==='1'?'✅ Good thinking!':'Try again.')}
if(id==='alphabet'){const L='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),W=['apple','ball','cat','dog','elephant','fish','grape','house','ice cream','juice','kite','lion','moon','nose','orange','pen','queen','rabbit','sun','tree','umbrella','van','water','xylophone','yellow','zebra'];p.innerHTML='<p class="lab-note">Grade 2 only: listen to each letter and its example word.</p><div class="lab-alphabet">'+L.map((l,i)=>'<div class="lab-letter"><b>'+l+'</b><span>'+W[i]+'</span><button class="lab-btn" data-a="'+l+'">🔊</button></div>').join('')+'</div><div class="lab-card" style="margin-top:14px"><h3>🔤 Alphabet Challenge</h3><p>Which letter starts <b id="aw"></b>?</p><div class="lab-game-options" id="ao"></div><div class="lab-feedback" id="af"></div></div>';p.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>speak(b.dataset.a+' as in '+W[L.indexOf(b.dataset.a)]));let ai=0;const alpha=()=>{const w=W[ai%26],c=L[ai%26],o=[c,L[(ai+3)%26],L[(ai+7)%26]].sort(()=>Math.random()-.5);p.querySelector('#aw').textContent=w;p.querySelector('#ao').innerHTML=o.map(x=>'<button class="lab-btn" data-al="'+x+'">'+x+'</button>').join('');p.querySelectorAll('[data-al]').forEach(b=>b.onclick=()=>{p.querySelector('#af').textContent=b.dataset.al===c?'✅ Correct!':'Not yet — try again.';if(b.dataset.al===c){ai++;setTimeout(alpha,250)}})};alpha()}
}
const target=document.querySelector('.g4-command')||document.querySelector('.mission-head')||document.querySelector('.map-head');if(target)target.insertAdjacentElement('afterend',root);show('texts');
})();
