/* MAGIC NEON AI ACADEMY — Live SVG Mission Reactor HUD 3.0 (visual-only) */
(function(){'use strict';
if(window.__EWMLessonHUD3)return;window.__EWMLessonHUD3=true;
var reduce=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
var selectors=['#modal','.g3-vocab-modal','.g4-vocab-modal'];
var lastKey='';
function visible(el){if(!el)return false;var s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'&&el.getBoundingClientRect().height>0}
function grade(){var p=(location.pathname||'').toLowerCase();return p.includes('grade4')?'G4':p.includes('grade3')?'G3':p.includes('grade2')?'G2':'CORE'}
function textOf(el){return ((el&&el.innerText)||'').replace(/\s+/g,' ').trim()}
function mission(modal){var t=textOf(modal),m=t.match(/(?:world|worlds)\s*([0-9]{1,2})[^0-9]{0,30}(?:mission|lesson)\s*([0-9]{1,2})/i);if(m)return 'WORLD '+String(m[1]).padStart(2,'0')+'  ·  MISSION '+String(m[2]).padStart(2,'0');var n=t.match(/(?:lesson|mission)\s*#?\s*([0-9]{1,2})/i);return n?'WORLD ??  ·  MISSION '+String(n[1]).padStart(2,'0'):'WORLD 01  ·  MISSION 01'}
function energy(modal){var t=textOf(modal),done=/(complete lesson|lesson complete|completed|congratulations|mission complete)/i.test(t);if(done)return 100;var total=(modal.querySelectorAll('.g3-option,.g4-option,.quiz-option,.option,.word-card,.g3-word,.g4-word').length)||10;var marked=modal.querySelectorAll('.selected,.correct,.answered,[aria-pressed="true"],[data-correct="true"]').length;return Math.max(5,Math.min(95,Math.round(10+(marked/Math.max(1,total))*85)))}
function state(modal,e){var t=textOf(modal),done=/(complete lesson|lesson complete|completed|congratulations|mission complete)/i.test(t);if(done)return ['COMPLETE','MISSION COMPLETE'];if(/quiz/i.test(t)&&e>55)return ['SURGE','QUIZ ENERGY SURGE'];return ['ACTIVE','LESSON ACTIVATED']}
function pulse(hud,cls){if(reduce)return;hud.classList.remove(cls);void hud.offsetWidth;hud.classList.add(cls);setTimeout(function(){hud.classList.remove(cls)},900)}
async function mount(modal){if(!visible(modal)||modal.querySelector(':scope > .lesson-mission-hud3'))return;var hud=document.createElement('div');hud.className='lesson-mission-hud3 enter';hud.setAttribute('aria-hidden','true');modal.appendChild(hud);try{var r=await fetch('/shared/lesson-mission-hud-3.svg?v=20260906-hud3');hud.innerHTML=await r.text();}catch(e){hud.remove();return}hud.classList.add('ready');setTimeout(function(){hud.classList.remove('enter')},700);refresh(modal,hud);}
function refresh(modal,hud){if(!hud||!hud.querySelector)return;var e=energy(modal),st=state(modal,e),wm=mission(modal),wmEl=hud.querySelector('#worldMission'),ef=hud.querySelector('#energyFill'),et=hud.querySelector('#energyText'),rs=hud.querySelector('#reactorStatus'),stEl=hud.querySelector('#statusText'),stateEl=hud.querySelector('#stateText');if(wmEl)wmEl.textContent=wm;if(ef){var w=Math.max(8,344*e/100);ef.setAttribute('width',String(w));}if(et)et.textContent=String(e).padStart(2,'0')+'%';if(rs)rs.textContent=st[0]==='COMPLETE'?'REACTOR OVERLOAD  ·  MISSION COMPLETE':st[0]==='SURGE'?'MISSION CORE SURGING  ·  QUIZ ACTIVE':'MISSION CORE ONLINE  ·  LESSON ACTIVE';if(stEl)stEl.textContent=st[0]==='COMPLETE'?'● REACTOR OVERLOAD':st[0]==='SURGE'?'● ENERGY SURGE':'● LESSON ACTIVATED';if(stateEl)stateEl.textContent='STATUS: '+st[0];var key=wm+'|'+st[0]+'|'+e;if(lastKey&&key!==lastKey&&wm!==lastKey.split('|')[0])pulse(hud,'world-shift');if(lastKey&&st[0]==='COMPLETE'&&lastKey.split('|')[1]!=='COMPLETE')pulse(hud,'overload');lastKey=key;}
function scan(){selectors.forEach(function(s){document.querySelectorAll(s).forEach(function(m){if(visible(m)){var h=m.querySelector(':scope > .lesson-mission-hud3');if(!h)mount(m);else refresh(m,h)}})})}
scan();new MutationObserver(function(){scan()}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style','aria-hidden','data-state']});setInterval(scan,900);
})();
